//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        public long ID { get; set; }
        public long idFast { get; set; }
        public long idEmpresa { get; set; }
        public string nombreEmpresa { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaAprobacion { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaFactura { get; set; }
        public string referenciaPresupuesto { get; set; }
        public string numeroOrden { get; set; }
        public string numeroFactura { get; set; }
        public string observacion { get; set; }
        public string usuCreacion { get; set; }
        public long ProveedorID { get; set; }
        public int EstadoCotizacionID { get; set; }
        public int DivisaID { get; set; }
        public string matricula { get; set; }
        public long kmActuales { get; set; }
        public decimal administracion { get; set; }
        public int IvaAdministracionID { get; set; }
        public bool refacturarIva { get; set; }
        public int RegionalID { get; set; }
        public string refacturacion { get; set; }
        public Nullable<System.DateTime> fechaRefacturacion { get; set; }
        public Nullable<System.DateTime> fechaOrden { get; set; }
        public decimal porcentajeDescuentoNomina { get; set; }
        public int cuotasDescuentoNomina { get; set; }
        public Nullable<System.DateTime> fechaInicioDescuentoNomina { get; set; }
        public Nullable<System.DateTime> fechaRegistroDescuentoNomina { get; set; }
        public decimal totalDescuentoNomina { get; set; }
        public long idFlota { get; set; }
        public string cobraAdministracion { get; set; }
        public Nullable<long> idIncidencia { get; set; }
        public int ResponsableCobroID { get; set; }
        public string actividadRealizarAntiguo { get; set; }
        public int actividadRealizarID { get; set; }
    
        public virtual ActividadRealizar ActividadRealizar { get; set; }
    }
}
